public with sharing class MockBillDetailResponse {
  public static String billAPIResponse =
    '[' +
    '{' +
    '"billId": "64fe8c72be1ae0125246d285",' +
    '"accountName": "Account 67",' +
    '"balance": "$336.08"' +
    '},' +
    '{' +
    '"billId": "64fe8c72703103b206105ebf",' +
    '"accountName": "Account 99",' +
    '"balance": "$151.97"' +
    '},' +
    '{' +
    '"billId": "64fe8c722fbe9ae981e5e418",' +
    '"accountName": "Account 105",' +
    '"balance": "$269.72"' +
    '}' +
    ']';
}
